name: bulbs
publish_to: 'none'

flutter:
  uses-material-design: true

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0